// src/app/projects/projects.component.ts
// import { Component } from '@angular/core';

// @Component({
//   selector: 'app-projects',
//   templateUrl: './projects.component.html',
//   styleUrl: './projects.component.css'
// })
// export class ProjectsComponent {
//   projectCards = [
//     {title: 'Savvy Swap', src: 'savvyswap.jpg', alt: 'Savvy Swap', backend:'https://github.com/LeeReyesCS/neighborhood-hack-backend', fronted: 'https://github.com/LeeReyesCS/neighborhood-hack-frontend', showDetailsButton: true },
//     {title: 'Yoga-4-All', src: 'yoga4all.jpg', alt: 'Yoga-4-All', link:'' },
//     {title: 'Inspiration Board', src: 'inspirationboard2.jpg', alt: 'Inspiration Board', link:'' },
//     {title: 'React Chat Log', src: 'reactchatlog.jpg', alt: 'React Chat Log', link:'' },
//     {title: 'Weather Report', src: 'weatherreport1.jpg', alt: 'Weather Report', link:'' },
//     {title: 'More on my Github', src: 'githubrepo.jpg', alt: 'More on My Github', link:'' }
//   ];

// // Function to handle the 'Show Details' button click
// showDetails(card: any) {
//   console.log('Showing details for:', card.title);
//   // You can implement logic to show more info or perform any action
//   }
// }

////NOTES://///
////We can use an array to handle the image data dynamically.
////I created a projectCards array with items of each card/image. 
////The images are dynamically rendered in the HTML with an *ngFor directive.
////But it's not quite working as expected...


////////////////////////////
import { Component } from '@angular/core';

@Component({
  selector: 'app-projects',
  imports: [],
  templateUrl: './projects.component.html',
  styleUrl: './projects.component.css'
})
export class ProjectsComponent {

}



<!-- <div class="container">
    <div class="row">
      <div class="col-lg-4 col-md-6 col-12 mt-4" *ngFor="let card of projectCards">
        <div class="card">
          <h4 class="card-title">{{ card.title }}</h4>
          <div class="card-body">
            <div class="text-center">
              <a href="{{ card.backend }}" class="btn btn-success" target="_blank">Backend</a>
              <img class="card-img-top" [src]="card.src" [alt]="card.alt" style="width:100%">
              
             <a href="{{ card.frontend }}" class="btn btn-primary mt-2" target="_blank">Frontend</a>
              
              <button class="btn btn-warning mt-2" (click)="showDetails(card)">Show Details</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div> -->

<!-- NOTES: 
Angular's *ngFor directivecan be used to dynamically render 
the cards/images. In your HTML file, add each card structure and 
bind to each card/image's properties or actions. 
-->

<!-- ************************************************** -->
<section id="projects">
    <div class="portfolio">
    <div class="container mt-3">
        <h1 class="text-center">Projects</h1>
        <div class="row">
            <div class="col-lg-4 mt-4">
                <div class="card">
                    <img class="card-img-top" src="petshome.jpg" alt="Card image" style="width:100%">
                    <div class="card-body">
                        <h4 class="card-title">Pets Project</h4>
                        <div class="text-center">
                            <a href="https://github.com/chemille/pet-project-django-react" class="btn btn-success">Backend</a>
                            <a href="https://github.com/chemille/pet-project-frontend" class="btn btn-success">Frontend</a>
                        </div>
                    </div>
                </div> 
            </div>
    
            <div class="col-lg-4 mt-4">
                <div class="card">
                    <img class="card-img-top" src="wildfiremain1.jpg" alt="Card image" style="width:100%">
                    <div class="card-body">
                        <h4 class="card-title">Wildfire Watchtower</h4>
                        <div class="text-center">
                            <a href="https://github.com/chemille/WildfireWatchtower" class="btn btn-success">Repo</a>
                            <a href="https://devpost.com/software/wildfire-tracker-xg3cmy" class="btn btn-success">Demo</a>
                            <a href="https://wildfirewatchtower-nb6t.onrender.com/" class="btn btn-success">Deployed link</a>
                        </div>
                    </div>
                </div>   
            </div>
    
            <div class="col-lg-4 mt-4">
                <div class="card">
                    <img class="card-img-top" src="savvyswap.jpg" alt="Card image" style="width:100%">
                    <div class="card-body">
                        <h4 class="card-title">Savvy Swap</h4>
                        <div class="text-center">
                            <a href="https://github.com/LeeReyesCS/neighborhood-hack-backend" class="btn btn-success">Backend</a>
                            <a href="https://github.com/LeeReyesCS/neighborhood-hack-frontend" class="btn btn-success">Frontend</a>
                            <a href="https://devpost.com/software/savvyswap" class="btn btn-success">Demo</a>
                        </div>
                    </div>
                </div>
            </div>
    
            <div class="col-lg-4 mt-4">
                <div class="card portfolioContent">
                    <img class="card-img-top" src="yoga4all.jpg" alt="Card image" style="width:100%">
                    <div class="card-body">
                        <h4 class="card-title">Yoga-4-All</h4>
                        <div class="text-center">
                            <a href="https://github.com/Farrah-Unger/Capstone-Yoga-4-All-Backend" class="btn btn-success">Backend</a>
                            <a href="https://github.com/chemille/frontend-yoga-4-all" class="btn btn-success">Frontend</a>
                            <a href="https://www.youtube.com/watch?v=CuP4NGSjDmQ" class="btn btn-success">Demo</a> 
                        </div>
                    </div>
                </div>
            </div>
    
            <div class="col-lg-4 mt-4">
                <div class="card portfolioContent">
                    <img class="card-img-top" src="inspirationboard2.jpg" alt="Card image" style="width:100%">
                    <div class="card-body">
                        <h4 class="card-title">Inspiration Board</h4>
                        <div class="text-center">
                            <a href="https://github.com/chemille/back-end-inspiration-board" class="btn btn-success">Backend</a>
                            <a href="https://github.com/chemille/front-end-inspiration-board" class="btn btn-success">Frontend</a>
                        </div>
                    </div>
                </div>
            </div>
    
        </div>
        
        <div class="row">
            <div class="col-lg-4 mt-4">
                <div class="card portfolioContent">
                    <img class="card-img-top" src="reactchatlog.jpg" alt="Card image" style="width:100%">
                    <div class="card-body">
                        <h4 class="card-title">React Chat Log</h4>
                        <div class="text-center">
                            <a href="https://github.com/chemille/react-chatlog" class="btn btn-success">Repo</a>
                        </div>
                    </div>
                </div>
            </div>
    
            <div class="col-lg-4 mt-4">
                <div class="card portfolioContent">
                    <img class="card-img-top" src="weatherreport1.jpg" alt="Card image" style="width:100%">
                    <div class="card-body">
                        <h4 class="card-title">Weather Report</h4>
                        <div class="text-center">
                            <a href="https://github.com/chemille/weather-report" class="btn btn-success">Repo</a>
                        </div>
                    </div>
                </div>
            </div>
    
            <div class="col-lg-4 mt-4">
                <div class="card portfolioContent">
                    <img class="card-img-top" src="githubrepo.jpg" alt="Card image" style="width:100%">
                    <div class="card-body">
                        <h4 class="card-title">More on my Github</h4>
                        <div class="text-center">
                            <a href="#" class="btn btn-success">Github Link</a>
                        </div>
                    </div>
                </div>
            </div>
    
        </div>
    </div>     
    
    <!-- Notes
    When the Angular app was created, it didn't come with an 
    assets folder under src. I tried making an assets folder 
    under src followed by editing the angular.json file; 
    however, it did not work. The only way the images will 
    display is by putting the images in the public folder. 
    Stack Overflow has a post about the same issue. 
    Apparently, previous versions of Ng came with the assets
    folder, but newer versions don't. Mine is v19.0.7
    -->

// src/components/Projects.jsx
import React from 'react';
import auroraborealis from '../images/auroraborealis.jpg';
import './projects.css';
import petshome from '../assets/petshome.jpg';
import wildfiremain1 from '../assets/wildfiremain1.jpg';
import savvyswap from '../assets/savvyswap.jpg';
import yoga4all from '../assets/yoga4all.jpg';
import inspirationboard2 from '../assets/inspirationboard2.jpg';
import reactchatlog from '../assets/reactchatlog.jpg';
import weatherreport1 from '../assets/weatherreport1.jpg';
import githubrepo from '../assets/githubrepo.jpg';
import ProjectCard from './ProjectCard';


export default function Projects() {
    const projectData = [
        {
            image: petshome,
            title: 'Pets Project',
            links: [
                { href: "https://github.com/chemille/pet-project-django-react", text: 'Backend'},
                { href: "https://github.com/chemille/pet-project-frontend", text: 'Frontend'},
            ]
        },
        {
            image: wildfiremain1,
            title: 'Wildfire Watchtower',
            links: [
                { href: "https://github.com/chemille/WildfireWatchtower" , text: 'Repo'},
                { href: "https://devpost.com/software/wildfire-tracker-xg3cmy", text: 'Demo'},
                { href: "https://wildfirewatchtower-nb6t.onrender.com/", text: 'Deployed Link'},
            ]
        },
        {
            image: savvyswap,
            title: 'Savvy Swap',
            links: [
                { href: "https://github.com/LeeReyesCS/neighborhood-hack-backend", text: 'Backend'},
                { href: "https://github.com/LeeReyesCS/neighborhood-hack-frontend", text: 'Frontend'},
                { href: "https://devpost.com/software/savvyswap", text: 'Demo'}
            ]
        },
        {
            image: yoga4all,
            title: 'Yoga-4-All',
            links: [
                { href: "https://github.com/Farrah-Unger/Capstone-Yoga-4-All-Backend", text: 'Backend'},
                { href: "https://github.com/chemille/frontend-yoga-4-all", text: 'Frontend'},
                { href: "https://www.youtube.com/watch?v=CuP4NGSjDmQ", text: 'Demo'}
            ]
        },
        {
            image: inspirationboard2,
            title: 'Inspiration Board',
            links: [
                { href: "https://github.com/chemille/back-end-inspiration-board", text: 'Backend'},
                { href: "https://github.com/chemille/front-end-inspiration-board", text: 'Frontend'}
            ]
        },
        {
            image: reactchatlog,
            title: 'React Chat Log',
            links: [
                { href: "https://github.com/chemille/react-chatlog", text: 'Repo'}
            ]
        },
        {
            image: weatherreport1,
            title: 'Weather Report',
            links: [
                { href: "https://github.com/chemille/weather-report", text: 'Repo'}
            ]
        },
        {
            image: githubrepo,
            title: 'More on my Github',
            links: [
                { href: "https://github.com/chemille", text: 'Github Link'}
            ]
        }
    ];

    return (
        <div style={{ backgroundImage: `url(${auroraborealis})`, backgroundSize: 'cover', width: '100vw'}} > 
            <div className="projects-container">
            <h1 className="text-center">Projects</h1>
            <div className="grid-container">
                {projectData.map((project, index) => (
                    <ProjectCard 
                        key={index}
                        image={project.image}
                        title={project.title}
                        links={project.links}
                    />
                ))}
            </div>
            </div>
        
        <div>
            <div className="photo-credit"><p>Photo by <a href="https://unsplash.com/@r3dmax?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Jonatan Pie</a> on <a href="https://unsplash.com/photos/person-standing-under-aurora-lights-UPWuKzAcuUI?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
            </p></div> 
            </div>
        </div>
    )
}
